### ISSUE TITLE
Strange parsing issue

### ISSUE THREAD

**Issue by cimeister** [delph-in/pydmrs#26]
When I try to parse the sentence  "My friend is young" using  `parse` from pydelphin_interface with either the 2018 or 1214 precompiled grammars (http://sweaglesw.org/linguistics/ace/), the word "young" seems to be identified as a proper noun. I thought initially that this might be something wrong with the grammar but when I directly use the ace binary, it returns the correct result. Even more strange, when I directly use the parse function from pydelphin, it returns the correct answer. Any idea why this might be happening?

**Comment by goodmami** [comment]
@cmeister747 pydmrs is calling PyDelphin pretty directly in order to parse with ACE, so it would be surprising if you see differences. I can think of two (unlikely) possibilities:

* if you don't supply the grammar image and happen to have one at [`/opt/erg/erg-1214.dat`](https://github.com/delph-in/pydmrs/blob/78ff791ffb0eefd6ea9d7d196e3003a7b562175c/pydmrs/__config__/default_interface.conf), then you might not be using the grammar you intended
* if you or pydmrs manipulate the input string in some way (e.g., capitalizing each word) this can influence the ERG's output to prefer named entities

However when I parse that sentence (as you have it above) I get the named entity "Young" as the first result, too. The second result (with the 2018 grammar) has the expected reading. The named-entity reading is not due to a bug in the grammar; it is a valid ambiguity (similar to "My friend is Smith"). So more likely is you were inspecting the final results from ACE and PyDelphin but the first result from pydmrs. Might that be the case?

**Comment by cimeister** [comment]
Thanks for the fast response, Michael! 

Yes, you're right; the script I had was only pulling the first result from pydmrs so I never saw the second. That was a careless mistake on my part. Sorry for the false alarm!
